### ISSUE TITLE
termios.error: 25について (Nohup使用時)

### ISSUE THREAD

**Issue by ghost** [posobot/bf_scalping#1]
素敵なBotありがとうございます。AWSで稼働させて伸るか反るか楽しんでいます。
実際に稼働しているときは利益がでたり、configの調整したりして色々思考錯誤しています。
(Todoも是非開発継続していただきたいです！)

件になりますが、
バックグランドで稼働したく、nohupを使いたいのですが、下記のようなエラーがでてしまうのですが、
どのように対処すればよろしいでしょうか。参考のURLなどあればご教授いただけると幸いです。

- - - -
Traceback (most recent call last):
  File "bftrade.py", line 149, in <module>
    key = func.get_key()
  File "/home/ubuntu/bf_scalping/func.py", line 14, in get_key
    attr_old = termios.tcgetattr(fno)
termios.error: (25, 'Inappropriate ioctl for device')
- - - -

**Comment by liiklin** [comment]
you can use tmux
